apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastapi-test
  description: FastAPI framework
  tags:
    - python
    - fastapi
    - api
  links:
    - url: https://fastapi-test.dev.tap-gitops.tanzu.dk/
      title: Base Url
      icon: dashboard
    - url: https://fastapi-test.dev.tap-gitops.tanzu.dk/docs
      title: Documentation
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=fastapi-accelerator
spec:
  type: service
  lifecycle: experimental
  owner: denmark-team
  system: demo
  providesApis:
    - kwhprice-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo
  description: Demo Application
spec:
  owner: denmark-team
  domain: cloud-apps
