apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: fastapi-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: fastapi-accelerator
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/TanzuDK/fastapi-test.git
      ref:
        branch: main
  params:
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/docs"
        owner: default-team
        description: "FastApi test"
